micronaut:
  application:
    name: pedidoService

grpc:
  channels:
    cliente:
      target: localhost:50051
      plaintext: true
    produto:
      target: localhost:50052
      plaintext: true
  server:
    port: 50053

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pedidoservice?useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

kafka.bootstrap.servers: localhost:9092